// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreateAt             []byte                `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	AccountId            string                `protobuf:"bytes,3,opt,name=accountId" json:"accountId,omitempty"`
	TotalPrice           float64               `protobuf:"fixed64,4,opt,name=totalPrice" json:"totalPrice,omitempty"`
	Products             []*Order_OrderProduct `protobuf:"bytes,5,rep,name=products" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetCreateAt() []byte {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *Order) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Order) GetTotalPrice() float64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetProducts() []*Order_OrderProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

type Order_OrderProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	Quantity             uint32   `protobuf:"varint,5,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderProduct) Reset()         { *m = Order_OrderProduct{} }
func (m *Order_OrderProduct) String() string { return proto.CompactTextString(m) }
func (*Order_OrderProduct) ProtoMessage()    {}
func (*Order_OrderProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{0, 0}
}
func (m *Order_OrderProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderProduct.Unmarshal(m, b)
}
func (m *Order_OrderProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderProduct.Marshal(b, m, deterministic)
}
func (dst *Order_OrderProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderProduct.Merge(dst, src)
}
func (m *Order_OrderProduct) XXX_Size() int {
	return xxx_messageInfo_Order_OrderProduct.Size(m)
}
func (m *Order_OrderProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderProduct.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderProduct proto.InternalMessageInfo

func (m *Order_OrderProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order_OrderProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_OrderProduct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order_OrderProduct) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order_OrderProduct) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type PostOderRequest struct {
	AccountId            string                          `protobuf:"bytes,2,opt,name=accountId" json:"accountId,omitempty"`
	Products             []*PostOderRequest_OrderProduct `protobuf:"bytes,4,rep,name=products" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PostOderRequest) Reset()         { *m = PostOderRequest{} }
func (m *PostOderRequest) String() string { return proto.CompactTextString(m) }
func (*PostOderRequest) ProtoMessage()    {}
func (*PostOderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{1}
}
func (m *PostOderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOderRequest.Unmarshal(m, b)
}
func (m *PostOderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOderRequest.Marshal(b, m, deterministic)
}
func (dst *PostOderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOderRequest.Merge(dst, src)
}
func (m *PostOderRequest) XXX_Size() int {
	return xxx_messageInfo_PostOderRequest.Size(m)
}
func (m *PostOderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostOderRequest proto.InternalMessageInfo

func (m *PostOderRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PostOderRequest) GetProducts() []*PostOderRequest_OrderProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

type PostOderRequest_OrderProduct struct {
	ProductId            string   `protobuf:"bytes,2,opt,name=productId" json:"productId,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOderRequest_OrderProduct) Reset()         { *m = PostOderRequest_OrderProduct{} }
func (m *PostOderRequest_OrderProduct) String() string { return proto.CompactTextString(m) }
func (*PostOderRequest_OrderProduct) ProtoMessage()    {}
func (*PostOderRequest_OrderProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{1, 0}
}
func (m *PostOderRequest_OrderProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOderRequest_OrderProduct.Unmarshal(m, b)
}
func (m *PostOderRequest_OrderProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOderRequest_OrderProduct.Marshal(b, m, deterministic)
}
func (dst *PostOderRequest_OrderProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOderRequest_OrderProduct.Merge(dst, src)
}
func (m *PostOderRequest_OrderProduct) XXX_Size() int {
	return xxx_messageInfo_PostOderRequest_OrderProduct.Size(m)
}
func (m *PostOderRequest_OrderProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOderRequest_OrderProduct.DiscardUnknown(m)
}

var xxx_messageInfo_PostOderRequest_OrderProduct proto.InternalMessageInfo

func (m *PostOderRequest_OrderProduct) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *PostOderRequest_OrderProduct) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type PostOderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOderResponse) Reset()         { *m = PostOderResponse{} }
func (m *PostOderResponse) String() string { return proto.CompactTextString(m) }
func (*PostOderResponse) ProtoMessage()    {}
func (*PostOderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{2}
}
func (m *PostOderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOderResponse.Unmarshal(m, b)
}
func (m *PostOderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOderResponse.Marshal(b, m, deterministic)
}
func (dst *PostOderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOderResponse.Merge(dst, src)
}
func (m *PostOderResponse) XXX_Size() int {
	return xxx_messageInfo_PostOderResponse.Size(m)
}
func (m *PostOderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostOderResponse proto.InternalMessageInfo

func (m *PostOderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{3}
}
func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(dst, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{4}
}
func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (dst *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(dst, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrdersForAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersForAccountRequest) Reset()         { *m = GetOrdersForAccountRequest{} }
func (m *GetOrdersForAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersForAccountRequest) ProtoMessage()    {}
func (*GetOrdersForAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{5}
}
func (m *GetOrdersForAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersForAccountRequest.Unmarshal(m, b)
}
func (m *GetOrdersForAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersForAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrdersForAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersForAccountRequest.Merge(dst, src)
}
func (m *GetOrdersForAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersForAccountRequest.Size(m)
}
func (m *GetOrdersForAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersForAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersForAccountRequest proto.InternalMessageInfo

func (m *GetOrdersForAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetOrdersForAccountResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersForAccountResponse) Reset()         { *m = GetOrdersForAccountResponse{} }
func (m *GetOrdersForAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersForAccountResponse) ProtoMessage()    {}
func (*GetOrdersForAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_d41615b65665bfb2, []int{6}
}
func (m *GetOrdersForAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersForAccountResponse.Unmarshal(m, b)
}
func (m *GetOrdersForAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersForAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetOrdersForAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersForAccountResponse.Merge(dst, src)
}
func (m *GetOrdersForAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersForAccountResponse.Size(m)
}
func (m *GetOrdersForAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersForAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersForAccountResponse proto.InternalMessageInfo

func (m *GetOrdersForAccountResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Order_OrderProduct)(nil), "pb.Order.OrderProduct")
	proto.RegisterType((*PostOderRequest)(nil), "pb.PostOderRequest")
	proto.RegisterType((*PostOderRequest_OrderProduct)(nil), "pb.PostOderRequest.OrderProduct")
	proto.RegisterType((*PostOderResponse)(nil), "pb.PostOderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "pb.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "pb.GetOrderResponse")
	proto.RegisterType((*GetOrdersForAccountRequest)(nil), "pb.GetOrdersForAccountRequest")
	proto.RegisterType((*GetOrdersForAccountResponse)(nil), "pb.GetOrdersForAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	PostOrder(ctx context.Context, in *PostOderRequest, opts ...grpc.CallOption) (*PostOderResponse, error)
	GetOrdersForAccount(ctx context.Context, in *GetOrdersForAccountRequest, opts ...grpc.CallOption) (*GetOrdersForAccountResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) PostOrder(ctx context.Context, in *PostOderRequest, opts ...grpc.CallOption) (*PostOderResponse, error) {
	out := new(PostOderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/PostOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersForAccount(ctx context.Context, in *GetOrdersForAccountRequest, opts ...grpc.CallOption) (*GetOrdersForAccountResponse, error) {
	out := new(GetOrdersForAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetOrdersForAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceServer interface {
	PostOrder(context.Context, *PostOderRequest) (*PostOderResponse, error)
	GetOrdersForAccount(context.Context, *GetOrdersForAccountRequest) (*GetOrdersForAccountResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_PostOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostOderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PostOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/PostOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PostOrder(ctx, req.(*PostOderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersForAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersForAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersForAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetOrdersForAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersForAccount(ctx, req.(*GetOrdersForAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostOrder",
			Handler:    _OrderService_PostOrder_Handler,
		},
		{
			MethodName: "GetOrdersForAccount",
			Handler:    _OrderService_GetOrdersForAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_order_d41615b65665bfb2) }

var fileDescriptor_order_d41615b65665bfb2 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xbd, 0x6e, 0xab, 0x30,
	0x14, 0x96, 0x49, 0x88, 0xc2, 0x21, 0xf7, 0xe6, 0xca, 0x89, 0xae, 0x10, 0x8d, 0x12, 0xc2, 0xc4,
	0x94, 0x81, 0x48, 0x1d, 0xaa, 0x0e, 0xcd, 0xd2, 0x9f, 0x29, 0x91, 0x2b, 0x75, 0x27, 0xe0, 0x01,
	0xa9, 0xc5, 0xc4, 0x36, 0x95, 0xfa, 0x02, 0x7d, 0x8c, 0x3e, 0x42, 0xd7, 0xbe, 0x5e, 0x85, 0x21,
	0x40, 0x28, 0x91, 0xba, 0x20, 0xfc, 0x1d, 0xfb, 0x7c, 0x3f, 0xc7, 0x06, 0x93, 0xf1, 0x88, 0xf2,
	0x55, 0xca, 0x99, 0x64, 0x58, 0x4b, 0xf7, 0xee, 0xa7, 0x06, 0xfa, 0x36, 0xc7, 0xf0, 0x5f, 0xd0,
	0xe2, 0xc8, 0x42, 0x0e, 0xf2, 0x0c, 0xa2, 0xc5, 0x11, 0xb6, 0x61, 0x18, 0x72, 0x1a, 0x48, 0xba,
	0x91, 0x96, 0xe6, 0x20, 0x6f, 0x44, 0xaa, 0x35, 0x9e, 0x81, 0x11, 0x84, 0x21, 0xcb, 0x12, 0xf9,
	0x10, 0x59, 0x3d, 0x75, 0xa4, 0x06, 0xf0, 0x1c, 0x40, 0x32, 0x19, 0x3c, 0xef, 0x78, 0x1c, 0x52,
	0xab, 0xef, 0x20, 0x0f, 0x91, 0x06, 0x82, 0x7d, 0x18, 0xa6, 0x9c, 0x45, 0x59, 0x28, 0x85, 0xa5,
	0x3b, 0x3d, 0xcf, 0xf4, 0xff, 0xaf, 0xd2, 0xfd, 0x4a, 0xc9, 0x28, 0xbe, 0xbb, 0xa2, 0x4c, 0xaa,
	0x7d, 0xf6, 0x3b, 0x82, 0x51, 0xb3, 0xf4, 0x43, 0x2e, 0x86, 0x7e, 0x12, 0xbc, 0x50, 0x25, 0xd5,
	0x20, 0xea, 0x1f, 0x3b, 0x60, 0x46, 0x54, 0x84, 0x3c, 0x4e, 0x65, 0xcc, 0x92, 0x52, 0x68, 0x13,
	0xc2, 0x53, 0xd0, 0xd3, 0x86, 0xca, 0x62, 0x91, 0x5b, 0x3f, 0x64, 0x41, 0x22, 0x63, 0xf9, 0x66,
	0xe9, 0x0e, 0xf2, 0xfe, 0x90, 0x6a, 0xed, 0x7e, 0x21, 0x18, 0xef, 0x98, 0x90, 0xdb, 0x88, 0x72,
	0x42, 0x0f, 0x19, 0x15, 0xad, 0x38, 0xb4, 0x76, 0x1c, 0xd7, 0x0d, 0xbb, 0x7d, 0x65, 0xd7, 0xc9,
	0xed, 0xb6, 0x9a, 0x9c, 0x33, 0x7e, 0xdf, 0xf2, 0x3d, 0x03, 0xa3, 0xac, 0xd5, 0x5c, 0x15, 0x70,
	0xa2, 0xbc, 0xd7, 0x52, 0xbe, 0x86, 0x7f, 0x35, 0xa7, 0x48, 0x59, 0x22, 0x28, 0x5e, 0x80, 0xae,
	0x6e, 0x84, 0x0a, 0xd2, 0xf4, 0x8d, 0x6a, 0x0e, 0xa4, 0xc0, 0xdd, 0x25, 0x8c, 0xef, 0xa8, 0x2c,
	0xa0, 0xd2, 0x6d, 0x2b, 0xf9, 0xbc, 0x6f, 0xbd, 0xe5, 0xb7, 0x7d, 0xaf, 0xc0, 0x3e, 0x1e, 0x12,
	0xb7, 0x8c, 0x6f, 0x8a, 0xb4, 0x3a, 0x03, 0x45, 0xad, 0x40, 0xdd, 0x1b, 0xb8, 0xe8, 0x3c, 0x5b,
	0x72, 0x2f, 0x61, 0xa0, 0x38, 0x84, 0x85, 0x54, 0xda, 0x0d, 0xf2, 0xb2, 0xe0, 0x7f, 0x1c, 0x6f,
	0xd3, 0x23, 0xe5, 0xaf, 0xf9, 0xc4, 0x2f, 0xc1, 0x50, 0xd9, 0xa8, 0x97, 0x30, 0xe9, 0x18, 0x8f,
	0x3d, 0x3d, 0x05, 0x4b, 0xae, 0x27, 0x98, 0x74, 0x48, 0xc1, 0xf3, 0x7c, 0xf3, 0x79, 0x7f, 0xf6,
	0xe2, 0x6c, 0xbd, 0xe8, 0xbb, 0x1f, 0xa8, 0x17, 0xba, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x41,
	0x60, 0xda, 0xd1, 0xb0, 0x03, 0x00, 0x00,
}
